{% set build = 0 %}
{% set version = "2022.03.15" %}

package:
  name: moose-pyhit
  version: {{ version }}

source:
  git_url: https://github.com/milljm/moose-pyhit.git

build:
  number: {{ build }}  # [linux,osx]
  skip: true           # [win]

requirements:
  build:
    - {{ moose_mpich }}
    - {{ moose_python }}
    - cython

  host:
    - {{ moose_mpich }}
    - {{ moose_python }}
    - cython

  run:
    - {{ moose_mpich }}
    - {{ pin_compatible('setuptools', lower_bound='58', upper_bound='60') }}
    - python

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
